[수정] server-side에 express 환경 구축
Akgop/SWEngineering-WebApp-Project-2021 pull request #13
Opened 2021-05-23 11:02 UTC by developerTae

이전에 express 프로젝트 생성할 때 ejs 옵션값을 안붙여서 수정하였습니다.

2021-05-23 11:23 UTC, Akgop requested changes
코드 수정 요청한 부분 수정해주세요~

2021-05-23 11:23 UTC, Akgop commented on server-side/views/index.ejs
> +</html>
EJS는 전혀 필요 없으니까 빼주세요!

2021-05-23 11:23 UTC, Akgop commented on server-side/routes/index.js
> +      res.render('index',  {title: 'test', rows: rows});
res.render 대신에 .json형식으로 데이터만 넘겨주는 방식으로 변경해주세요

2021-05-23 13:14 UTC, developerTae commented
커맨트 반영하여 수정했으니 확인해주세요!

2021-05-23 14:15 UTC, Akgop approved these changes

2021-05-24 00:02 UTC, developerTae commented
서버 측 port번호 변경

2021-05-24 02:10 UTC, YuHyeonGeun-KOR commented
확인하였습니다.

2021-05-24 02:11 UTC, YuHyeonGeun-KOR reviewed
확인했습니다.

2021-05-24 02:12 UTC, YuHyeonGeun-KOR approved these changes

2021-05-24 02:12 UTC, merged